version: "2.15.1"
services:
  express-app:
    ports:
      - "3000:3000"
    container_name: express-app-container
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: anas
      MONGO_INITDB_ROOT_PASSWORD: 1234
    container_name: mongo-container
    volumes:
      - ./mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: anas
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://anas:1234@mongo:27017/
    depends_on:
      - mongo